name: Automated Release ⭐

on:
  push:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Executable
    runs-on: windows-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. PyInstaller를 사용한 exe 빌드
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: --onefile, --windowed, --noconsole, --add-data web:web, --icon icon.ico

      # 3. 빌드 결과물을 artifacts에 복사
      - name: Archive Executable
        run: |
          mkdir artifacts
          move dist\main.exe artifacts\main.exe

      # 4. GitHub Release 생성 및 업로드
      - name: Create Release and Upload Executable
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create $TAG `
            --repo "$REPO" `
            --title "Release ${TAG#v}" `
            --notes "Automatically generated release." `
            artifacts\main.exe
