name: Automated Release

on:
  push:  # 모든 Push 이벤트에서 실행

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  # Windows와 macOS에서 빌드 실행
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 의존성 설치
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. PyInstaller로 실행 파일 빌드 (OS 구분)
      - name: Build Executable
        shell: bash  # 모든 OS에서 실행 가능하도록 Bash로 지정
        run: |
          echo "Running on $RUNNER_OS"
          if [ "$RUNNER_OS" = "Windows" ]; then
            pyinstaller --onefile --windowed --noconsole --add-data web:web --icon icon.ico --upx-dir upx main.py
          elif [ "$RUNNER_OS" = "macOS" ]; then
            pyinstaller --onefile --windowed --noconsole --add-data web:web --upx-dir upx main.py
          fi

      # 5. 빌드 결과를 artifacts 디렉터리에 복사 및 압축 (OS 구분)
      - name: Archive and Compress Executable
        shell: bash
        run: |
          mkdir -p artifacts
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/main.exe artifacts/main-windows.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            # .app 폴더를 zip으로 압축
            cd dist  # dist 폴더로 이동
            zip -r ../artifacts/main-macos.zip main.app  # 상위 폴더의 artifacts에 압축
            cd .. # 다시 루트 디렉토리로
          fi

      # 6. 자동 태그 생성 및 릴리스 생성
      - name: Create Release and Upload Executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # 현재 시간 기반 태그 생성
          version=$(date +%Y%m%d-%H%M%S)  # 형식: yyyyMMdd-HHmmss
          tag="v$version"

          # 태그 푸시
          git tag $tag
          git push origin $tag

          # Release 생성
          if [ "$RUNNER_OS" = "Windows" ]; then
            gh release create "$tag" \
              --title "Windows Release: $version" \
              --notes "Automatically generated release for Windows." \
              artifacts/main-windows.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            gh release create "$tag" \
              --title "MacOS Release: $version" \
              --notes "Automatically generated release for MacOS." \
              artifacts/main-macos.zip  # 압축된 파일 업로드
          fi
