name: Automated Release ⭐

on:
  push:
    tags:
      - v*  # v로 시작하는 태그 푸시 시 실행

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Executable
    runs-on: windows-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. PyInstaller로 실행 파일 빌드
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: --onefile, --windowed, --noconsole, --add-data web:web, --icon icon.ico

      # 3. 빌드된 실행 파일을 artifacts 디렉토리로 복사
      - name: Archive Executable
        run: |
          mkdir artifacts
          move dist\main.exe artifacts\main.exe

      # 4. 릴리스를 생성하고 실행 파일 업로드
      - name: Create Release and Upload Executable
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.ref_name }} # 트리거된 태그 이름으로 설정됨
        run: |
          if ($TAG -match '^v[0-9]+(\.[0-9]+)*$') {
            gh release create $TAG `
              --repo "$REPO" `
              --title "Release ${TAG#v}" `
              --notes "Automatically generated release." `
              artifacts\main.exe
          }
          else {
            Write-Error "Invalid tag name: $TAG. Expected a version tag like v1.0.0"
          }
