name: Automated Release ⭐

on:
  push:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Executable
    runs-on: windows-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. PyInstaller를 사용한 exe 빌드
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: --onefile, --windowed, --noconsole, --add-data web:web, --icon icon.ico

      # 3. 빌드된 실행 파일 저장
      - name: Archive Executable
        run: |
          mkdir artifacts
          mv dist/main.exe artifacts/
        shell: bash

      # 4. 릴리스 생성 및 실행 파일 업로드
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --repo="$REPO" \
              --title="Release ${TAG#v}" \
              --notes "Automatically generated release." \
              ./artifacts/main.exe
