name: Automated Build ⭐

on:
  push:
    branches: [ main ]

jobs:

  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: --onefile, --windowed, --noconsole, --add-data web:web, --icon icon.ico

      - name: Archive Executable
        run: |
          mkdir artifacts
          mv dist/main.exe artifacts/
        shell: bash

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # 릴리스 태그 이름
          release_name: "Release v1.0.0" # 릴리스 이름
          draft: false
          prerelease: false
      
      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./artifacts/main.exe
          asset_name: main.exe
          asset_content_type: application/octet-stream
