name: 자동 빌드 & 릴리스

on:
  push:

permissions:
  contents: write

jobs:
  Windows-Build:
    name: Windows 빌드
    runs-on: windows-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      # 2. Python 환경 설정
      - name: Python 환경 구축
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 실행 파일 빌드
        shell: bash
        run: pyinstaller --onefile --windowed --noconsole --add-data web:web --add-data font:font --icon icon.ico --upx-dir upx main.py

      - name: 실행 파일 이동
        shell: bash
        run: |
          mkdir artifacts
          mv dist/main.exe artifacts/main-windows.exe

      - name: 첨부파일 업로드
        uses: actions/upload-artifact@v4
        with:
          name: Windows-build
          path: artifacts/main-windows.exe

  macOS-Build:
    name: macOS 빌드
    runs-on: macos-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Python 환경 구축
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 실행 파일 빌드
        shell: bash
        run: pyinstaller --onefile --windowed --noconsole --add-data web:web --icon icon.icns main.py

      - name: 실행 파일 이동 및 압축
        shell: bash
        run:  |
          mkdir artifacts
          zip -j artifacts/main-macos.zip dist/*

      - name: 첨부파일 업로드
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: artifacts/main-macos.zip

  create-release:
    name: 릴리스 생성
    needs: ['Windows-Build', 'macOS-Build']
    runs-on: ubuntu-latest
    steps:
      - name: 첨부파일 다운로드 (Windows)
        uses: actions/download-artifact@v4
        with:
          name: Windows-build
          path: artifacts/windows

      - name: 첨부파일 다운로드 (macOS)
        uses: actions/download-artifact@v4
        with:
          name: macOS-build
          path: artifacts/macos

      - name: 릴리스 생성
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows/main-windows.exe
            artifacts/macos/main-macos.zip
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "자동 생성된 Windows 및 MacOS 빌드"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}